Adds learner testimonials component for interior pages
mitodl/mit-open pull request #1001
Opened 2024-06-03 20:38 UTC by jkachel

### What are the relevant tickets?

Closes mitodl/hq#4457

### Description (What does it do?)

This adds a component that can be included on any page to display testimonials, and then adds that to the `FieldPage` component so it should display on the field search pages (which includes offeror pages, I think).

### Screenshots (if appropriate):

Screenshots are of the component on the homepage since my local search is broken. 

Desktop:

![image](https://github.com/mitodl/mit-open/assets/945611/c0b6b7d0-8b29-4d0f-a963-c2f2a6a39966)

Mobile:

![image](https://github.com/mitodl/mit-open/assets/945611/cc7bdb80-06ce-4011-8420-f62843c98562)

### How can this be tested?

You will need to configure your app with testimonial data. This can be anything; you just need records in there.

You should see the testimonial card on the offeror pages - for example, http://od.odl.local:8063/c/offeror/ocw/ . You should only see testimonials that are attached to that particular offeror. You should be able to paginate through them, and the design should match the design in Figma. 

You should also see the testimonial card on the search pages as well; there, it should show all the testimonials. 

### Additional Context

- I added a bit of margin on top of the pager buttons - this isn't in the Figma but they were sort of getting stuck too close to the name block.
- You can also test this by adding the testimonial card to the homepage (which is what I did for testing, since my search is broken). Look in `mit-open/src/pages/FieldPage/FieldPage.tsx` to see how but you really just have to drop the component in anywhere in there.

2024-06-11 17:24 UTC, ChristopherChudzicki requested changes
The testimonials look great. I did notice some issues with their display when there's only a single testimonial, and it seems like we are displaying it more places than we should.

2024-06-11 17:24 UTC, ChristopherChudzicki commented on frontends/mit-open/src/page-components/TestimonialCard/TestimonialCard.tsx
> +          "You have three powerful forces coming together again, the HBCUs, and MIT, Merlot. The need is worldwide for people of all races, underrepresented populations to be able to access informati
`quote`, `attestant_name`, `title` are all required, right? Let's drop the fallbacks.

2024-06-11 17:24 UTC, ChristopherChudzicki commented on frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
> +        />
I believe that only offeror ("unit") pages should have Testimonial. Other channel pages, like "Departments" do not.

Figma for Department Detail pages:
<img width="616" alt="Screenshot 2024-06-11 at 1 19 20 PM" src="https://github.com/mitodl/mit-open/assets/9010790/31b4ebaf-9df8-4ef7-a60a-def151918ad9">

But this is showing all testimonials for department pages (and topic pages).

<img width="1178" alt="Screenshot 2024-06-11 at 1 20 10 PM" src="https://github.com/mitodl/mit-open/assets/9010790/306b5839-3334-4d88-9694-43ffc3e7e9ec">

2024-06-11 17:24 UTC, ChristopherChudzicki commented on frontends/mit-open/src/page-components/TestimonialCard/TestimonialCard.tsx
> +        <Slider
When there is only 1 testimonial, I don't think we should use a slider. We don't want buttons, and it seems to cause problems (more on this in a sec).

So I suggest: `{data.results.length === 1 ? : < InteriorTestimonialCard /> : <Slider ... />}`


### Carousel misbehaves with a single slide

When there's only one testimonial, I get:

<img width="1272" alt="Screenshot 2024-06-11 at 11 43 35 AM" src="https://github.com/mitodl/mit-open/assets/9010790/47f636e2-2b27-47a0-880a-8108b873d9ad">

Crazy. Works great for 2+ slides.

2024-06-11 17:24 UTC, ChristopherChudzicki commented on frontends/mit-open/src/page-components/TestimonialCard/TestimonialCard.tsx
> +  if (!data) return null
Let's also bail early if no testimonials.

```suggestion
  if (!data) return null
  if (data.results.length === 0) return null
```

2024-06-11 17:24 UTC, ChristopherChudzicki commented on frontends/mit-open/src/page-components/TestimonialCard/TestimonialCard.tsx
Small comment... To me, the testimonial display does not seem like "Cards". Cards are usually narrow and displayed with many visible at once.

I'd call this TestimonialDisplay or something.

Or TestimonialCarousel (even though I suggest we not use a carousel if there's only 1).

2024-06-11 19:53 UTC, jkachel commented
These should all be resolved now.

2024-06-12 12:08 UTC, ChristopherChudzicki requested changes

2024-06-12 12:08 UTC, ChristopherChudzicki commented on frontends/mit-open/src/pages/FieldPage/FieldPage.tsx
> +        ) : null}
Could you rebase? (May be easier to squash and then rebase).

This should now be `channelType === "unit"`.

2024-06-13 19:52 UTC, ChristopherChudzicki approved these changes
If you have time, I think it would be great to add a few tests to this. Some things I would test:
1. `TestimonialDisplay.test.tsx`
    - displays nothing if no testimonials
    - displays data if 1
    - displays carousel if many
2. `FieldPage.test.tsx`
    - Displays a carousel if channel type is unit
    - otherwise does not. 
        - "Otherwise does not" can be tricky. Could give the testimonials a `data-testid`. Or could spy on `TestimonialDisplay` and assert not called.

2024-06-13 19:52 UTC, ChristopherChudzicki commented on frontends/mit-open/src/page-components/TestimonialDisplay/TestimonialDisplay.tsx
> +import { Attestation } from "api/v0"
```suggestion
import type { Attestation } from "api/v0"
```
IMO `type` imports are nice when you only need the type. The are 100% guaranteed to have no impact at runtime (whereas `import { Attestation } from "api/v0"` can have an impact even if you're only importing a type, if `api/v0` has side effects.)

Also makes intent clear.

2024-06-14 12:36 UTC, merged

2024-06-14 12:37 UTC, jkachel commented
Merging this now because there's some stuff that needs to change a bit (the attestant stuff needs to be pulled into its own component for the homepage) - will add tests while I do that. (Also, we changed "offeror" to "unit" so need to do that too.)