Add profile edit page
mitodl/mit-open pull request #1029
Opened 2024-06-07 19:19 UTC by rhysyngsun

### What are the relevant tickets?

### Description (What does it do?)

This adds the profile edit page 

### Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

### How can this be tested?

### Additional Context

2024-06-17 17:00 UTC, shanbady requested changes
when I change values for either of these select boxes the label doesnt appear to update (hitting save still updates them to whatever they are set to)
<img width="964" alt="Screenshot 2024-06-17 at 12 55 31 PM" src="https://github.com/mitodl/mit-open/assets/196425/ba2bc784-968f-43b9-855f-5def0a3ccb96">

2024-06-17 17:00 UTC, shanbady commented on frontends/ol-components/src/index.ts
> +export { useTheme } from "@mui/material/styles"
This doesnt appear to be necessary

2024-06-17 21:28 UTC, rhysyngsun commented
@shanbady addressed those issues

2024-06-18 15:10 UTC, shanbady approved these changes
looks god

2024-06-18 15:26 UTC, merged