Modularize learning resource serializers
mitodl/mit-open pull request #117
Opened 2023-10-03 13:01 UTC by rhysyngsun

# What are the relevant tickets?

Prep work for #36 

# Description (What does it do?)

This splits up `learning_resources/serializers.py` into several modules instead of one monolithic one:

- They are partitioned them roughly on the type of learning resource (podcasts and podcast episodes share a module).
- I've implemented a `lazy.py` module that tracks lazy references to serializers. This functions similarly to passing a model reference by string to `ForeignKey` and friends. This eliminates some gymnastics that were being done to avoid circular references.

# Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

# How can this be tested?

# Additional Context

2023-10-23 14:30 UTC, ChristopherChudzicki requested changes
Still looking through changes, but I think
```
learning_resources/serializers.py
learning_resources/serializers_test.py
```
should be deleted.

Locally I deleted these and regenerated openapi—no changes. So I don't think these files were affecting anything, really.

2023-10-23 17:18 UTC, ChristopherChudzicki requested changes
This looks great to me. The new serializer structure makes sense and the openapi / typescript is much more accurate.

I do think it would be worth resolving the "`resource_type` too wide on ProgramResource, CourseResource, etc types" issue. Currently, `ProgramResource`, `LearningPathResource`, etc, aren't assignable to `LearningResource`, which is... inconvenient (e.g., suppressed errors in the frontend factories). But we don't need to resolve it here.

Noticed a few minor issues (see code comments). Also, one question and one bug:

---

#### Question
 I noticed this error
```
/src/learning_resources/serializers/learning_resources.py:236: Warning [LearningPathItemsViewSet > LearningPathRelationshipSerializer > LearningResourceSerializer]: Encountered 2 components with identical names "LearningResource" and different classes <class 'learning_resources.serializers.learning_resources.LearningResourceSerializer'> and <class 'drf_spectacular.utils.PolymorphicProxySerializer'>. This will very likely result in an incorrect schema. Try renaming one.
```
when running `./scripts/generate_openapi.sh`. Do you know what's going on with that?

#### Bug?
1. Visit http://localhost:8063/api/v1/learningpaths/ *Or the frontend form at http://localhost:8063/learningpaths/*
2. Create a learning path, either by form or by POSTing someting like `{ "title": "Hello, world!" }`
3. Check the response. `resource_type` is `""`. Should be `"learning_path"`.
4.

2023-10-23 17:18 UTC, ChristopherChudzicki commented on frontends/api/src/test-utils/factories/learningResources.ts
> +      return program(overrides)
Could you add a better note here? Something about the individual resource types (ProgramResource, CourseResource...) having a `resource_type` wider than it should be.

2023-10-23 20:41 UTC, mbertrand commented
I rebased with main (which this PR needs to resolve some conflicts) and ran all the ETL pipelines, didn't notice any problems.

2023-10-25 18:48 UTC, ChristopherChudzicki commented on Dockerfile-node
>  FROM node:16.20.1
```suggestion
FROM node:18.18.2
```
We updated this recently in docker-compose to match Heroku.

2023-11-25 18:05 UTC, rhysyngsun commented
Closing in favor of #244 244

2023-11-25 18:05 UTC, closed without merging