adjust / refactor channel detail header
mitodl/mit-open pull request #1234
Opened 2024-07-09 01:25 UTC by gumaerc

### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/4781

### Description (What does it do?)
This PR refactors `ChannelPageSkeleton.tsx` into two separate files; `DefaultChannelSkeleton.tsx` and `UnitChannelSkeleton.tsx`. The reason for this is that the layout of the `Banner` sections of the Unit channels is different enough that it was starting to become difficult to make changes to the Unit specific layout without affecting the other types of channels. This defines a clear separation so that Unit channels that have more extensive branding / styling can be customized without worrying about affecting the other types of channel pages. The use of `BannerPage` was replaced with simply using the newer `Banner` component. Slots were added to `Banner` to allow customization in the way the Unit channel pages need. Lastly the original problem noted in the issue above was addressed, which was just that the non-Unit channel page banners looked off from the design.

### Screenshots (if appropriate):
![image](https://github.com/mitodl/mit-open/assets/12089658/c5689025-c2f8-4b13-ae2d-b4e9680fb5b7)
![image](https://github.com/mitodl/mit-open/assets/12089658/1f392618-e68e-4a87-a14d-86706688d3b2)
![image](https://github.com/mitodl/mit-open/assets/12089658/b6f60446-7eac-4464-b1d6-b527a0c62a6d)
![image](https://github.com/mitodl/mit-open/assets/12089658/18e5d9cc-89d8-46a6-9eb8-2c371f79265f)
![image](https://github.com/mitodl/mit-open/assets/12089658/a47ee900-bd4a-452a-86d8-8d43e56215df)
![image](https://github.com/mitodl/mit-open/assets/12089658/519ae958-d724-477d-90af-90cda9ea2ed3)

### How can this be tested?
 - Spin up `mit-open` on this branch
 - Ensure your departments, topics and units are populated
   - `docker compose exec web ./manage.py update_offered_by`
   - `docker compose exec web ./manage.py update_topics`
   - `docker compose exec web ./manage.py update_departments_schools`
 - Visit the home page at http://localhost:8062/
 - Click the icon to open the nav menu, then click "By Topic"
 - Select any of the topics and verify that the text in the banner does not shift and lines up with the listing page
 - Click the icon to open the menu again and click "By Provider"
 - Click any of the units on the listing page
 - Verify that the layout of the unit channel pages has not changed
 - Repeat this process on mobile from the home page step

2024-07-09 14:42 UTC, shanbady commented on frontends/mit-open/src/pages/ChannelPage/UnitChannelSkeleton.tsx
> +const Page = styled.div({})
do we need a named component here or can we wrap in an empty <></>

2024-07-09 14:50 UTC, shanbady commented on frontends/mit-open/src/pages/ChannelPage/UnitChannelSkeleton.tsx
> +export const ChannelTitleRow = styled.div`
seems like we have this duplicated. it would be nice to consolidate this along with the other duplicated elements such as ChannelControls

2024-07-09 14:50 UTC, shanbady requested changes
Code changes look good. I did notice 2 things. Seems like the "manage widgets" link in the settings/gear tooltip isnt working. I checked on rc and it seems its also broken there. 

The other thing i noticed in mobile view for certain pages (ones with longer breadcrumbs), the breadcrumb appears to break apart .
<img width="222" alt="Screenshot 2024-07-09 at 10 33 27 AM" src="https://github.com/mitodl/mit-open/assets/196425/cc01ab67-31e8-41ef-be93-2b7ea00dae52">

2024-07-09 15:13 UTC, ChristopherChudzicki commented on frontends/mit-open/src/pages/ChannelPage/DefaultChannelSkeleton.tsx
@gumaerc Would you mind changing this and the other filename to something other than "Skeleton"? "Template" or "Layout" would be good, IMO.

I'd like to stop using Skeleton since it's what people call the style of loading states we use, e.g., https://mui.com/material-ui/react-skeleton/

2024-07-09 15:18 UTC, ChristopherChudzicki commented on frontends/ol-components/src/components/Banner/Banner.tsx
> +  subHeaderTypography?: ResponsiveStyleValue<string | undefined>
"subheader" (and "subheading") are usually one word, so `subheader` w/o camel would be better.

2024-07-09 15:18 UTC, ChristopherChudzicki commented on frontends/ol-components/src/components/Banner/Banner.tsx
Could you also update the Banner story to use `subheader` not description? Annoying you didn't get any TS errors from Storybook.

Would be great to add another story or two, too.

2024-07-09 15:20 UTC, ChristopherChudzicki commented on frontends/ol-components/src/components/Banner/Banner.tsx
@gumaerc Apparently if you do `Meta<typeof Banner>` it will give better TS errors / support:

<img width="1030" alt="Screenshot 2024-07-09 at 11 20 17 AM" src="https://github.com/mitodl/mit-open/assets/9010790/08527bf6-2e38-41c0-b9d8-219003ad654d">

2024-07-09 18:31 UTC, shanbady commented
> Code changes look good. I did notice 2 things. Seems like the "manage widgets" link in the settings/gear tooltip isnt working. I checked on rc and it seems its also broken there.
> 
> The other thing i noticed in mobile view for certain pages (ones with longer breadcrumbs), the breadcrumb appears to break apart . <img alt="Screenshot 2024-07-09 at 10 33 27 AM" width="222" src="https://private-user-images.githubusercontent.com/196425/347002384-cc01ab67-31e8-41ef-be93-2b7ea00dae52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTAxNDUsIm5iZiI6MTcyMDU0OTg0NSwicGF0aCI6Ii8xOTY0MjUvMzQ3MDAyMzg0LWNjMDFhYjY3LTMxZTgtNDFlZi1iZTkzLTJiN2VhMDBkYWU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxODMwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTg4MzMxM2ZjMTY3NDMzYjgwZTNhZTRhYzAwYWI2NTFlMWQxMGRiZGRkZDNmYWEzMzRlMjczMTdjOTc0YmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cyS_A2Jua2jAhhqkghNErISHnC5JTKO5RF94otRp5ZU">

looks like there is a separate ticket for removing the widget settings button https://github.com/mitodl/hq/issues/4730

2024-07-09 20:07 UTC, gumaerc commented
@shanbady @ChristopherChudzicki Thanks for your reviews, this is ready for another look now.

2024-07-10 13:34 UTC, shanbady approved these changes
👍

2024-07-11 13:37 UTC, merged