Remove learning_format, use delivery for search filter/facet
mitodl/mit-open pull request #1567
Opened 2024-09-16 20:23 UTC by mbertrand

### What are the relevant tickets?
Part 2 of https://github.com/mitodl/hq/issues/5126

### Description (What does it do?)
- Uses an updated version of course-search-utils (https://github.com/mitodl/course-search-utils/pull/123, needs to be merged before this one)
- Removes the `learning_format` field from `LearningResource` and `Profile` models
- Removes "learning_format" from the ETL pipelines 
- Updates the frontend to use "delivery" instead of "learning_format" for filtering and facets

### Screenshots (if appropriate):
<img width="952" alt="Screenshot 2024-09-16 at 4 19 07 PM" src="https://github.com/user-attachments/assets/39f3eb38-8eb6-4b4b-92bf-258bd24c003a">

<img width="914" alt="Screenshot 2024-09-16 at 4 22 14 PM" src="https://github.com/user-attachments/assets/3caae998-a790-4102-9379-2f20459841f9">

### How can this be tested?
- Run some searches, with and without using the "Delivery" facet, everything should work as expected.
- Update your delivery format for your user profile, everything should work as expected.

### Additional Context

2024-09-18 14:03 UTC, shanbady requested changes
Seems like [this factory attribute](https://github.com/mitodl/mit-open/blob/ad1ef032902b2f3b76b132afb6c9d979cfa48d4a/frontends/api/src/test-utils/factories/learningResources.ts#L156) still remains but otherwise looks good

2024-09-18 18:15 UTC, mbertrand commented
@shanbady that "format" factory attribute is for `LearningResourceOfferor.format` which is not quite the same thing as `LearningResource.learning_format`.  I made a bunch of changes based on feedback from Simone, because some more planning has to go into how the switchover to "delivery" will be presented on the front end:

- Removed all "offline" values from courses via a migration and updated the OCW ETL pipeline to not add it unless `OCW_OFFLINE_DELIVERY=True` (default=`False`)
- Reverted "Format"->"Delivery" frontend text changes
- Updated `package.json` and `yarn.lock` to use the official new version of `course-search-utils`

2024-09-18 18:30 UTC, shanbady approved these changes

2024-09-19 16:43 UTC, abeglova approved these changes
lgtm

2024-09-19 17:46 UTC, merged