[NextJS] Load correct font and a few other global things
mitodl/mit-open pull request #1583
Opened 2024-09-18 21:10 UTC by ChristopherChudzicki

### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/5473

### Description (What does it do?)
This PR:
- loads the correct font for MIT Learn
- Adds a noindex tag, based on MITOL_NOINDEX
- Loads APPZI based on `NEXT_PUBLIC_APPZI_URL`.

### How can this be tested?
1. View any page in the app and inspect text. Check that the Neue Haas Grotesk font is being used. 
    - Checking what font is actually used is a little tricky. Here's how you can do it in Chrome dev tools.
2. In your env file, set `NEXT_PUBLIC_APPZI_URL="https://w.appzi.io/w.js?token=Q2pSI"` *(this is not a secret env var, hence NEXT_PUBLIC and client side availability)*. Restart NextJS / Docker. The Appzi feedback form should appear on enter-right, just like prod.
3. Set `MITOL_NOINDEX=true` in your env file. and restart NextJS / Docker. The site should now include a noindex tag in `<head>`

<!--- Uncomment and add steps to be completed before merging this PR if necessary
### Checklist:
- [ ] Check with Jon about `NEXT_PUBLIC_*` values for docker container.

2024-09-19 18:52 UTC, shanbady approved these changes
approving - pending conflict resolution with nextjs

2024-09-19 19:14 UTC, shanbady requested changes
It seems the frontend doesnt come up in a codespace. its possible that some of the env variables need to get added to the env/codespaces.env

2024-09-20 13:11 UTC, ChristopherChudzicki commented
> It seems the frontend doesnt come up in a codespace. its possible that some of the env variables need to get added to the env/codespaces.env

Probably is env var issue. I think this is worth fixing, but we should handle it in a separate PR.

2024-09-20 13:46 UTC, shanbady approved these changes
I'll create a separate issue for getting the codespaces to work. I'm guessing some of it may have to do with the hostname settings etc

2024-09-20 15:26 UTC, merged