Change default ordering parameter to "sortby", add options documentation to learning_resources endpoint
mitodl/mit-open pull request #221
Opened 2023-11-16 16:30 UTC by mbertrand

# What are the relevant tickets?
Closes #220 

# Description (What does it do?)
- Changes the default DRF ordering parameter to "sortby"
- modifies the `LearningResourceFilter` class to also handle the sortby parameter and provide choices that drf_spectacular can translate to better schema documentation

# Screenshots (if appropriate):

![Screenshot 2023-11-16 at 11 12 33 AM](https://github.com/mitodl/mit-open/assets/187676/93487c97-ccb7-49eb-a5f3-3b01021cf1be)

![Screenshot 2023-11-16 at 11 13 32 AM](https://github.com/mitodl/mit-open/assets/187676/31efe0cd-e761-47b9-b233-2e230a2c8803)

![Screenshot 2023-11-16 at 11 14 42 AM](https://github.com/mitodl/mit-open/assets/187676/0f6165ba-d3e4-4cd9-8372-2322e206bd00)

# How can this be tested?
Try the following urls, they should return results in the expected sort order based on the specified value:
http://localhost:8063/api/v1/learning_resources/?sortby=-id
http://localhost:8063/api/v1/learning_resources/?sortby=readable_id
http://localhost:8063/api/v1/learning_resources/?sortby=-last_modified
http://localhost:8063/api/v1/learning_resources/?sortby=start_date
http://localhost:8063/api/v1/learning_resources/?sortby=start_date

Check the swagger and redoc documentation, they should look like screenshots above.

2023-11-16 18:56 UTC, abeglova requested changes

2023-11-16 18:56 UTC, abeglova commented on learning_resources/constants.py
> +LEARNING_RESOURCE_SORTBY_OPTIONS = {
Can you make these changes to the learning_resource search endpoint as well. Also does it make sense for both endpoints to have the same sort options?

2023-11-17 18:46 UTC, mbertrand commented on learning_resources/constants.py
> +    "mitcoursenumber": {
For the database rest api, this will always sort on the first(primary) course number.

2023-11-17 18:48 UTC, mbertrand commented on learning_resources/models.py
> +
Moved the above here from `LearningResourceViewSet` so that they can also be used when bulk upserting into the search index.

2023-11-17 18:49 UTC, mbertrand commented on learning_resources_search/api.py
> +        .replace("__", ".")
These values have to be adjusted to work correctly with opensearch.

2023-11-17 19:11 UTC, mbertrand commented on learning_resources/etl/utils.py
> +                "sort_coursenum": sort_coursenum,
Adding these fields to the `course.course_numbers` field so they can be used by the database REST API too

2023-11-17 19:12 UTC, mbertrand commented on learning_resources/etl/utils.py
> +                "primary": idx == 0,
Adding these fields to the `course.course_numbers` field so they can be used by the database REST API too

2023-11-17 19:14 UTC, mbertrand commented on learning_resources_search/serializers.py
> +            SearchCourseNumberSerializer(instance=num).data
Add back the `course_number` fields that are omitted by `CourseNumberSerializer`

2023-11-17 19:15 UTC, mbertrand commented on learning_resources_search/serializers.py
> +        ]
Add back the `course_number` fields that are omitted by `CourseNumberSerializer`

2023-11-17 19:16 UTC, mbertrand commented on learning_resources_search/serializers.py
> +        .filter(id__in=ids)
Hoping that `select_related` and `prefetch_related` here might make the queries more efficient.

2023-11-20 17:27 UTC, abeglova approved these changes
LGTm

2023-11-20 19:42 UTC, merged