Adapt resource cards for new API format
mitodl/mit-open pull request #49
Opened 2023-08-23 20:53 UTC by ChristopherChudzicki

#### What are the relevant tickets?
#41 

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2023-08-24 17:46 UTC, ChristopherChudzicki commented on frontends/infinite-corridor/src/infinite-pages/HomePage.test.tsx
I decided just to remove this.

This page **is** useful as a reference, but we have it in https://github.com/mitodl/open-discussions and at https://discussions-rc.odl.mit.edu/infinite. We don't need it here, too.

2023-08-24 17:48 UTC, ChristopherChudzicki commented on frontends/ol-search-ui/assets/learning-resource-card.scss
The change here is that all the rules are nested under `..ol-lrc-root-old ` now.

2023-08-25 16:00 UTC, abeglova requested changes

2023-08-25 16:00 UTC, abeglova commented on frontends/ol-learning-resources/src/components/LearningResourceCard.tsx
> +import React, { useCallback } from "react"
Do we need a version of LearningResourceCard both here and in infinite-corridor/components? Also is this LearningResourceCard used anywhere? the Home.tsx uses the other one

2023-08-25 17:27 UTC, ChristopherChudzicki commented on frontends/ol-learning-resources/src/utils/index.ts
> +const findBestRun = (
I'm not sure. I would prefer logic like this on the backend. On the other hand, for an API consumable by outside world, the sorting we do
>  prefer current, then nearest future, then nearest past.
seems a little arbitrary / specific.

2023-08-25 18:46 UTC, abeglova approved these changes
lgtm

2023-08-25 18:48 UTC, merged