2: remove discussions backend code, reddit, channels, moira, notifications
mitodl/mit-open pull request #64
Opened 2023-08-30 16:19 UTC by collinpreston

#### Pre-Flight checklist
- [ ] Testing
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
https://github.com/mitodl/mit-open/issues/2

#### What's this PR do?

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

2023-09-06 18:52 UTC, mbertrand requested changes
> Should ckeditor remain or be removed?

I'd defer to @ChristopherChudzicki on that, but I think there's a chance we might want it for field channels and/or their widgets?

> Should uploading to S3 functionality remain or be removed?

Are you referring to `MITOPEN_USE_S3` and `DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"`?  I think we should keep that, for when FieldChannel images are uploaded, and maybe user profile images too (unless keycloak will be replacing that part).

2023-09-06 18:52 UTC, mbertrand commented on embedly/views.py
> -from embedly.api import get_embedly_summary, THUMBNAIL_URL
You can probably delete the constant `THUMBNAIL_URL` from `embedly.api`

2023-09-06 18:52 UTC, mbertrand commented on search/management/commands/update_index.py
> +        """Index Courses"""
"""Index all learning resources"""?

2023-09-06 19:01 UTC, ChristopherChudzicki commented
> > Should ckeditor remain or be removed?

>I'd defer to @ChristopherChudzicki on that, but I think there's a chance we might want it for field channels and/or their widgets?

I would keep it. The API endpoint gives us a key for CKEditor's image upload service, which we may well continue to use.

2023-09-07 14:26 UTC, mbertrand approved these changes
LGTM! 👍

2023-09-07 14:51 UTC, merged