ContentFiles for edx/ocw learning resources
mitodl/mit-open pull request #68
Opened 2023-09-05 15:54 UTC by mbertrand

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Closes #18 

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2023-09-06 20:01 UTC, mbertrand commented on learning_resources/serializers.py
> +class ContentFileSerializer(serializers.ModelSerializer):
There are some fields not included here that will be required for opensearch (namely, `resource_relations` that indicates the parent-child relationship between the parent course and the contentfile). My thinking is that there will still be a `search.serializers.OSContentFileSerializer` that could inherit from this serializer and add that field.  Let me know if you'd prefer all the fields required for opensearch to be defined here.

2023-09-08 15:20 UTC, abeglova requested changes
One comment, otherwise lgtm

2023-09-12 16:48 UTC, abeglova approved these changes
LGTM

2023-09-12 16:48 UTC, abeglova commented
Sorry, I thought I already approved this...

2023-09-12 17:21 UTC, merged